# NOTE: Sensitive values such as passwords, JWT secrets, and mail credentials are omitted.
# This is a demonstration configuration for portfolio purposes only.

server:
  port: 8443
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store: classpath:keystore.p12      # Upload your keystore file to resources
    key-store-password: changeit           # Set your secure keystore password
    key-store-type: PKCS12
    key-alias: tomcat
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/nms_core      # Update as needed
    username: nms_app                                # Update as needed
    password: changeme                               # Set secure DB password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          lob:
            non_contextual_creation: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    cors:
      allowed-origins: "https://your-domain.com,http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "Content-Type,Authorization,X-Requested-With,Accept,Origin"
      allow-credentials: true
      max-age: 3600

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.example.com
    port: 587
    username: user@example.com              # Replace with your mail username
    password: changeme                      # Replace with your mail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  websocket:
    allowed-origins: "*"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    rs.nms.newsroom: DEBUG
    org.springframework.security: WARN
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-history: 30
    max-size: 10MB

jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-chars
  access-token:
    expiration: 900000       # 15 min
  refresh-token:
    expiration: 2592000000   # 30 days

tcp:
  server:
    port: 5555
    max-frame-length: 8192

user:
  default-password: changeme
  default-role: JOURNALIST

file:
  upload-dir: uploads/
  max-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    filter: true

rate-limiter:
  enabled: true
  capacity: 100
  refill-rate: 10
  refill-duration: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    enable:
      http: true
      jvm: true
      process: true
      system: true

mos:
  tcp:
    port: 10540

frontend:
  url: http://localhost:3000